version: '3.8'

services:
  app:
    build: .
    container_name: myapp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=${JWT_SECRET}
      - DB_URI=${DB_URI}
    depends_on:
      - db
      - redis

  db:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
